version: '2'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0'
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  kibana:
    image: 'docker.elastic.co/kibana/kibana-oss:7.0.0'
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
  
  redis:
    image: 'redis:4.0.9'
    container_name: redis
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "always"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata1:/data

volumes:
  esdata1:
    driver: local
  redisdata1:
    driver: local
